#!/bin/sh
# $Id$

CONF=/usr/local/share/rng-c/arx.conf

files=$*

if [ -z "$files" ] ; then
  cat > /tmp/xck.$$
  files=/tmp/xck.$$
fi

for x in $files
do
  rnv -q `arx $x $CONF` $x
done
rm /tmp/xck.$$ 2>/dev/null
